python:
  - 3.5
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
install:
- pip install pytest coveralls
- pip install .
script:
- coverage run --source=viresclient setup.py pytest
after_success:
- coveralls
