language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install pytest coveralls
- pip install .
script:
- coverage run --source=viresclient setup.py py.test
after_success:
- coveralls
