language: python
python:
- '3.5'
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
- pip install pytest coveralls
- pip install .
script:
- coverage run --source=viresclient setup.py pytest
after_success:
- coveralls
