matrix:
    include:
        - python: 3.5
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true
install:
- pip install tox-travis
- pip install pytest coveralls
- pip install .
script: tox
- coverage run --source=viresclient setup.py pytest
after_success:
- coveralls
