name: CI

on:
  push:
    branches: [ v0.10.0-prep ]
  pull_request:
    branches: [ v0.10.0-prep ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nox
        uses: excitedleigh/setup-nox@v2.0.0
      - name: Run Nox
        run: nox
