name: Test Latest

on:
  workflow_dispatch:
  schedule:
    # Weekly on Sunday
    - cron: '0 0 * * 0'

jobs:
  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04", "macos-14", "windows-2022"]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      run: python -m pip install .[test]
    - name: Configure token access
      run: |
        viresclient set_token "https://vires.services/ows" ${{ secrets.VIRES_TOKEN_SWARM }}
        viresclient set_default_server https://vires.services/ows
    - name: Test package
      run: python -m pytest -ra
